SyncPage[Model](
    data=[
        Model(
            id="text-search-babbage-doc-001",
            created=1651172509,
            object="model",
            owned_by="openai-dev",
        ),
        Model(
            id="gpt-3.5-turbo-16k-0613",
            created=1685474247,
            object="model",
            owned_by="openai",
        ),
        Model(
            id="curie-search-query",
            created=1651172509,
            object="model",
            owned_by="openai-dev",
        ),
        Model(
            id="gpt-3.5-turbo-16k",
            created=1683758102,
            object="model",
            owned_by="openai-internal",
        ),
        Model(
            id="text-search-babbage-query-001",
            created=1651172509,
            object="model",
            owned_by="openai-dev",
        ),
        Model(id="babbage", created=1649358449, object="model", owned_by="openai"),
        Model(
            id="babbage-search-query",
            created=1651172509,
            object="model",
            owned_by="openai-dev",
        ),
        Model(
            id="text-babbage-001", created=1649364043, object="model", owned_by="openai"
        ),
        Model(
            id="text-similarity-davinci-001",
            created=1651172505,
            object="model",
            owned_by="openai-dev",
        ),
        Model(
            id="gpt-4-1106-preview",
            created=1698957206,
            object="model",
            owned_by="system",
        ),
        Model(
            id="davinci-similarity",
            created=1651172509,
            object="model",
            owned_by="openai-dev",
        ),
        Model(
            id="code-davinci-edit-001",
            created=1649880484,
            object="model",
            owned_by="openai",
        ),
        Model(
            id="curie-similarity",
            created=1651172510,
            object="model",
            owned_by="openai-dev",
        ),
        Model(
            id="babbage-search-document",
            created=1651172510,
            object="model",
            owned_by="openai-dev",
        ),
        Model(
            id="curie-instruct-beta",
            created=1649364042,
            object="model",
            owned_by="openai",
        ),
        Model(
            id="gpt-3.5-turbo", created=1677610602, object="model", owned_by="openai"
        ),
        Model(
            id="gpt-3.5-turbo-1106",
            created=1698959748,
            object="model",
            owned_by="system",
        ),
        Model(
            id="text-search-ada-doc-001",
            created=1651172507,
            object="model",
            owned_by="openai-dev",
        ),
        Model(
            id="davinci-instruct-beta",
            created=1649364042,
            object="model",
            owned_by="openai",
        ),
        Model(
            id="text-similarity-babbage-001",
            created=1651172505,
            object="model",
            owned_by="openai-dev",
        ),
        Model(
            id="text-search-davinci-doc-001",
            created=1651172505,
            object="model",
            owned_by="openai-dev",
        ),
        Model(
            id="babbage-similarity",
            created=1651172505,
            object="model",
            owned_by="openai-dev",
        ),
        Model(
            id="text-embedding-ada-002",
            created=1671217299,
            object="model",
            owned_by="openai-internal",
        ),
        Model(
            id="davinci-search-query",
            created=1651172505,
            object="model",
            owned_by="openai-dev",
        ),
        Model(
            id="gpt-4-vision-preview",
            created=1698894917,
            object="model",
            owned_by="system",
        ),
        Model(
            id="text-similarity-curie-001",
            created=1651172507,
            object="model",
            owned_by="openai-dev",
        ),
        Model(id="gpt-4", created=1687882411, object="model", owned_by="openai"),
        Model(
            id="text-davinci-001", created=1649364042, object="model", owned_by="openai"
        ),
        Model(
            id="text-search-davinci-query-001",
            created=1651172505,
            object="model",
            owned_by="openai-dev",
        ),
        Model(
            id="ada-search-document",
            created=1651172507,
            object="model",
            owned_by="openai-dev",
        ),
        Model(
            id="ada-code-search-code",
            created=1651172505,
            object="model",
            owned_by="openai-dev",
        ),
        Model(id="babbage-002", created=1692634615, object="model", owned_by="system"),
        Model(id="davinci-002", created=1692634301, object="model", owned_by="system"),
        Model(
            id="davinci-search-document",
            created=1651172509,
            object="model",
            owned_by="openai-dev",
        ),
        Model(
            id="curie-search-document",
            created=1651172508,
            object="model",
            owned_by="openai-dev",
        ),
        Model(
            id="babbage-code-search-code",
            created=1651172509,
            object="model",
            owned_by="openai-dev",
        ),
        Model(
            id="text-search-ada-query-001",
            created=1651172505,
            object="model",
            owned_by="openai-dev",
        ),
        Model(
            id="code-search-ada-text-001",
            created=1651172507,
            object="model",
            owned_by="openai-dev",
        ),
        Model(
            id="babbage-code-search-text",
            created=1651172509,
            object="model",
            owned_by="openai-dev",
        ),
        Model(
            id="code-search-babbage-code-001",
            created=1651172507,
            object="model",
            owned_by="openai-dev",
        ),
        Model(
            id="ada-search-query",
            created=1651172505,
            object="model",
            owned_by="openai-dev",
        ),
        Model(
            id="ada-code-search-text",
            created=1651172510,
            object="model",
            owned_by="openai-dev",
        ),
        Model(id="tts-1-hd", created=1699046015, object="model", owned_by="system"),
        Model(
            id="text-search-curie-query-001",
            created=1651172509,
            object="model",
            owned_by="openai-dev",
        ),
        Model(
            id="text-davinci-002", created=1649880484, object="model", owned_by="openai"
        ),
        Model(
            id="text-davinci-edit-001",
            created=1649809179,
            object="model",
            owned_by="openai",
        ),
        Model(
            id="code-search-babbage-text-001",
            created=1651172507,
            object="model",
            owned_by="openai-dev",
        ),
        Model(
            id="tts-1-hd-1106", created=1699053533, object="model", owned_by="system"
        ),
        Model(
            id="whisper-1",
            created=1677532384,
            object="model",
            owned_by="openai-internal",
        ),
        Model(
            id="gpt-3.5-turbo-instruct-0914",
            created=1694122472,
            object="model",
            owned_by="system",
        ),
        Model(id="ada", created=1649357491, object="model", owned_by="openai"),
        Model(
            id="gpt-3.5-turbo-0613",
            created=1686587434,
            object="model",
            owned_by="openai",
        ),
        Model(id="text-ada-001", created=1649364042, object="model", owned_by="openai"),
        Model(
            id="canary-whisper", created=1699656801, object="model", owned_by="system"
        ),
        Model(
            id="ada-similarity",
            created=1651172507,
            object="model",
            owned_by="openai-dev",
        ),
        Model(
            id="code-search-ada-code-001",
            created=1651172507,
            object="model",
            owned_by="openai-dev",
        ),
        Model(
            id="text-similarity-ada-001",
            created=1651172505,
            object="model",
            owned_by="openai-dev",
        ),
        Model(
            id="gpt-3.5-turbo-0301",
            created=1677649963,
            object="model",
            owned_by="openai",
        ),
        Model(
            id="gpt-3.5-turbo-instruct",
            created=1692901427,
            object="model",
            owned_by="system",
        ),
        Model(id="gpt-4-0613", created=1686588896, object="model", owned_by="openai"),
        Model(
            id="text-search-curie-doc-001",
            created=1651172509,
            object="model",
            owned_by="openai-dev",
        ),
        Model(
            id="text-davinci-003",
            created=1669599635,
            object="model",
            owned_by="openai-internal",
        ),
        Model(
            id="text-curie-001", created=1649364043, object="model", owned_by="openai"
        ),
        Model(id="curie", created=1649359874, object="model", owned_by="openai"),
        Model(id="gpt-4-0314", created=1687882410, object="model", owned_by="openai"),
        Model(id="canary-tts", created=1699492935, object="model", owned_by="system"),
        Model(
            id="tts-1", created=1681940951, object="model", owned_by="openai-internal"
        ),
        Model(id="davinci", created=1649359874, object="model", owned_by="openai"),
        Model(id="dall-e-2", created=1698798177, object="model", owned_by="system"),
        Model(id="tts-1-1106", created=1699053241, object="model", owned_by="system"),
        Model(id="dall-e-3", created=1698785189, object="model", owned_by="system"),
    ],
    object="list",
)
